# https://github.com/chabad360/hugo-gh-pages
name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          branch: master
          hugoVersion: 'extended_0.74.3' # Locked version, see issue #363
          repo: numpy/numpy.github.com
          siteDir: /github/workspace/public
          githubToken: ${{ secrets.PERSONAL_TOKEN }}